const codeLangMap = {
  '': 'none',
  actionscript3: 'actionscript3',
  bash: 'bash',
  sh: 'bash',
  csharp: 'csharp',
  coldfusion: 'coldfusion',
  cpp: 'cpp',
  css: 'css',
  delphi: 'delphi',
  diff: 'diff',
  erlang: 'erlang',
  groovy: 'groovy',
  html: 'html',
  java: 'java',
  javafx: 'javafx',
  javascript: 'javascript',
  js: 'javascript',
  json: 'JSON',
  perl: 'perl',
  php: 'php',
  powershell: 'powershell',
  python: 'python',
  ruby: 'ruby',
  scala: 'scala',
  shell: 'bash',
  sql: 'sql',
  vb: 'vb',
  xml: 'xml',
  mermaid: 'mermaid',
}

export default codeLangMap
